#!/bin/bash

# Skript väljastab 5 rea ja 5 tärniga ruudu

for (( i=1; i<=5; i++ )); do

    # Väljastame rea numbri
    echo -n "$i. "

    # Sisemine tsükkel väljastab reale 5 tärni
    for (( j=1; j<=5; j++ )); do
        echo -n "* "
    done

    # Liigume järgmisele reale
    echo ""

done
