#!/bin/bash

# Skript küsib ridade ja tärnide arvu ning väljastab vastava kujundi

read -p "Sisesta ridade arv: " read_arv
read -p "Sisesta tärnide arv reas: " tarnide_arv

for (( i=1; i<=read_arv; i++ )); do

    echo -n "$i. "

    for (( j=1; j<=tarnide_arv; j++ )); do
        echo -n "* "
    done

    echo ""

done
