#!/bin/bash

# Skript arvutab arvude 1 kuni 10 paarisarvude summa

summa=0

for (( arv=1; arv<=10; arv++ )); do

    # Kontrollime, kas arv jagub kahega ilma jäägita
    if (( arv % 2 == 0 )); then
        summa=$((summa + arv))
    fi

done

echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"
